const SEED_DATA = {
  accounts: [
    "Consumer/Personal Checking 1123996-S08",
    "Business Checking 861-S01",
    "Business Savings 861-S00",
    "Business Credit Card 861-L90",
    "Consumer Mastercard 996-L91",
    "Other / To confirm"
  ],
  categories: [
    "Mortgage / Rent",
    "Utilities",
    "Phone / Internet",
    "Insurance",
    "Software / Subscriptions",
    "Credit Card Payment",
    "Loan / Financing",
    "Transportation / Tolls",
    "Property / Maintenance",
    "Tax",
    "Personal / Household",
    "Other"
  ],
  statuses: ["Upcoming", "Paid", "Overdue", "Autopay", "Review", "Paused"],
  priorities: ["High", "Medium", "Low"],
  classifications: ["Business", "Personal", "Mixed", "Review"],
  frequencies: ["Monthly", "Weekly", "Biweekly", "Quarterly", "Annual", "One-time", "Variable"],
  bills: [
    {
      id: "bill-crosscountry",
      name: "CrossCountry Mortgage",
      category: "Mortgage / Rent",
      amount: 2753.28,
      dueDate: "2026-07-01",
      frequency: "Monthly",
      account: "Business Checking 861-S01",
      autopay: "Check",
      status: "Review",
      priority: "High",
      classification: "Mixed",
      notes: "Seeded from historical Business Checking pattern. Confirm exact due date and business/personal split."
    },
    {
      id: "bill-peco",
      name: "PECO Energy",
      category: "Utilities",
      amount: 300.00,
      dueDate: "2026-07-10",
      frequency: "Monthly",
      account: "Business Checking 861-S01",
      autopay: "Check",
      status: "Upcoming",
      priority: "High",
      classification: "Mixed",
      notes: "Estimated amount. Confirm statement due date."
    },
    {
      id: "bill-tmobile",
      name: "T-Mobile",
      category: "Phone / Internet",
      amount: 220.00,
      dueDate: "2026-07-12",
      frequency: "Monthly",
      account: "Business Checking 861-S01",
      autopay: "Check",
      status: "Upcoming",
      priority: "Medium",
      classification: "Mixed",
      notes: "Seeded from recurring transactions."
    },
    {
      id: "bill-verizon",
      name: "Verizon",
      category: "Phone / Internet",
      amount: 150.00,
      dueDate: "2026-07-15",
      frequency: "Monthly",
      account: "Business Checking 861-S01",
      autopay: "Check",
      status: "Upcoming",
      priority: "Medium",
      classification: "Mixed",
      notes: "Confirm account and due date."
    },
    {
      id: "bill-simply-business",
      name: "Simply Business Insurance",
      category: "Insurance",
      amount: 188.88,
      dueDate: "2026-07-16",
      frequency: "Monthly",
      account: "Business Credit Card 861-L90",
      autopay: "Check",
      status: "Upcoming",
      priority: "High",
      classification: "Business",
      notes: "Seeded from Business Credit Card pattern."
    },
    {
      id: "bill-adobe",
      name: "Adobe",
      category: "Software / Subscriptions",
      amount: 24.37,
      dueDate: "2026-07-20",
      frequency: "Monthly",
      account: "Business Credit Card 861-L90",
      autopay: "Check",
      status: "Upcoming",
      priority: "Low",
      classification: "Business",
      notes: "Confirm plan and amount."
    },
    {
      id: "bill-grasshopper",
      name: "Grasshopper Phone",
      category: "Phone / Internet",
      amount: 60.72,
      dueDate: "2026-07-22",
      frequency: "Monthly",
      account: "Business Credit Card 861-L90",
      autopay: "Check",
      status: "Upcoming",
      priority: "Medium",
      classification: "Business",
      notes: "Seeded from Business Credit Card pattern."
    },
    {
      id: "bill-ezpass",
      name: "PTC EZPass",
      category: "Transportation / Tolls",
      amount: 200.00,
      dueDate: "2026-07-25",
      frequency: "Variable",
      account: "Business Credit Card 861-L90",
      autopay: "Check",
      status: "Review",
      priority: "Medium",
      classification: "Mixed",
      notes: "Variable toll replenishment. Confirm business-use percentage."
    },
    {
      id: "bill-amex",
      name: "AMEX Payment",
      category: "Credit Card Payment",
      amount: 500.00,
      dueDate: "2026-07-18",
      frequency: "Monthly",
      account: "Business Checking 861-S01",
      autopay: "No",
      status: "Review",
      priority: "High",
      classification: "Review",
      notes: "Seeded from payment patterns. Confirm account and minimum due."
    },
    {
      id: "bill-capital-one",
      name: "Capital One Payment",
      category: "Credit Card Payment",
      amount: 350.00,
      dueDate: "2026-07-21",
      frequency: "Monthly",
      account: "Business Checking 861-S01",
      autopay: "No",
      status: "Review",
      priority: "High",
      classification: "Review",
      notes: "Seeded from payment patterns. Confirm exact due date."
    },
    {
      id: "bill-apple-card",
      name: "Apple Card / GS Bank",
      category: "Credit Card Payment",
      amount: 500.00,
      dueDate: "2026-07-30",
      frequency: "Monthly",
      account: "Business Checking 861-S01",
      autopay: "No",
      status: "Review",
      priority: "High",
      classification: "Review",
      notes: "Seeded from payment patterns. Confirm amount and source account."
    },
    {
      id: "bill-geico",
      name: "GEICO Auto",
      category: "Insurance",
      amount: 190.00,
      dueDate: "2026-07-28",
      frequency: "Monthly",
      account: "Business Checking 861-S01",
      autopay: "Check",
      status: "Upcoming",
      priority: "Medium",
      classification: "Mixed",
      notes: "Confirm vehicle/business-use allocation."
    }
  ],
  payments: []
};
